clone:
  git:
    image: plugins/git:next
workspace:
  base: /toolkit
  path: demo
services:
  web:
    image: fpfis/php56-dev
    environment:
      - DOCUMENT_ROOT=/toolkit/demo/build
  mysql:
    image: percona/percona-server:5.6
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
pipeline:
  solr:
    image: fpfis/solr5
    group: prepare
    detach: true
  selenium:
    image: selenium/standalone-chrome
    group: prepare
    detach: true
  build:
    image: fpfis/php56-dev
    group: prepare
    secrets: [ ASDA_USER, ASDA_PASS ]
    commands:
      - rm -rf .git
      - wget -q https://$${ASDA_USER}:$${ASDA_PASS}@asda.fpfis.tech.ec.europa.eu/$${DOWNSTREAM_OWNER}/$${DOWNSTREAM_REPO}/build/build-dev-$${DOWNSTREAM_BRANCH}.tar.gz
      - wget -q https://$${ASDA_USER}:$${ASDA_PASS}@asda.fpfis.tech.ec.europa.eu/$${DOWNSTREAM_OWNER}/$${DOWNSTREAM_REPO}/dumps/dump-dev-$${DOWNSTREAM_BRANCH}.tar.gz
      - tar -xzf build-dev-$${DOWNSTREAM_BRANCH}.tar.gz
      - tar -xzf dump-dev-$${DOWNSTREAM_BRANCH}.tar.gz
  install:
    image: fpfis/php56-dev
    group: demo
    commands:
      - ./toolkit/phing drush-settings-generate -D'project.url.base'='https://${DRONE_REPO_NAME}-${DRONE_BUILD_NUMBER}-${DRONE_JOB_NUMBER}.ci.fpfis.tech.ec.europa.eu' -logger phing.listener.AnsiColorLogger
      - ./toolkit/drush -r build sql-create -y
      - ./toolkit/drush -r build sqlc < /toolkit/demo/dump.sql
      - ./toolkit/drush -r build uli
  tunnel:
    image: fpfis/drone-frpc-plugin:latest
    group: demo
    secrets: [ frpc_token, frpc_server ]
    environment:
      - PLUGIN_ENDPOINT=web:8080
      - PLUGIN_GEN_AUTH=yes
      - PLUGIN_DOMAIN=${DRONE_REPO_NAME}-${DRONE_BUILD_NUMBER}-${DRONE_JOB_NUMBER}.ci.fpfis.tech.ec.europa.eu
      - PLUGIN_URL_OUTPUT_FILE=/toolkit/demo/.frpc