clone:
  git:
    image: plugins/git:next
workspace:
  base: /test
  path: downstream
services:
  web:
    image: fpfis/php71-build
    environment:
      - TOOLKIT_ENV_PROPS=/test/downstream/vendor/ec-europa/toolkit/includes/phing/props/drone.props
matrix:
  REPOSITORY:
    - agm-reference
    - agri-eip-reference
    - amr-reference
    - anti-fraud-reference
    - antitrafficking-reference
    - argiculture-reference
    - basext-reference
    - cem-reference
    - chafea-reference
    - cim-reference
    - clima-reference
    - comm-digitaltransformation-blog-reference
    - commpo-reference
    - consular-protection-reference
    - creativeeurope-reference
    - crosportal-reference
    - culture-reference
    - daphne-toolkit-reference
    - devco-reference
    - digit-ict-reference
    - digital-agenda-reference
    - dm-trainet-reference
    - dms-reference
    - dt_brp_reference
    - dt_cwt_reference
    - dt_info_reference
    - dt_pol_reference
    - eac-eqf-reference
    - eac-eyp-reference
    - eacea-site-reference
    - easme-site-reference
    - echo-site-reference
    - ecn-brief-reference
    - eco-innovation-projects-reference
    - ecoap_stayconnected-reference
    - edpb-reference
    - edpsweb-reference
    - education2-reference
    - eductraining-reference
    - eeas-reference
    - efsa-reference
    - eiopa-reference
    - eip-aha-reference
    - ejtp-reference
    - ema-reference
    - emnies-reference
    - encasia-reference
    - ener-reference
    - enrd-reference
    - env-efe-reference
    - epale-reference
    - epsc-reference
    - epso-reference
    - epsocontact-reference
    - era-reference
    - erasmusplus-reference
    - erasmusplus2-reference
    - ersc-reference
    - esf-tc-reference
    - euandme-reference
    - eu-aid-reference
    - eu-invest-reference
    - euetfa-reference
    - eufinance-reference
    - euip-reference
    - euprojects-reference
    - europaeu-reference
    - europahub-reference
    - eurydice-reference
    - eusdgs-reference
    - eusinglesky-reference
    - euvp-reference
    - ewrc-reference
    - expert-pane-reference
    - eych-reference
    - farnet-reference
    - food-animals-plants-reference
    - fpi-reference
    - fra-reference
    - futurium-reference
    - globalstrategy-reference
    - grid-communications-toolkit-reference
    - growth-reference
    - health-reference
    - home-affairs-reference
    - horizon2020-reference
    - hr-contact-reference
    - iee-projects-reference
    - inforegio-reference
    - inea-reference
    - inseparable-reference
    - isa-reference
    - jrccties-reference
    - jrcsh-reference
    - kci-reference
    - know4pol-reference
    - mare-emd-reference
    - mare-magaz-reference
    - mariecurie-actions-reference
    - mariecurie2-reference
    - maritime-affaires-reference
    - maritimeforum-reference
    - microdata-reference
    - migr-fisheries-reference
    - migr-move-reference
    - mossportal-reference
    - n-lex-migration-reference
    - near-reference
    - newsroom-reference
    - oil-mit-reference
    - organic-reference
    - pics-reference
    - pmo-contact-reference
    - ppcm-reference
    - primeinfrastructure-reference
    - publicare-reference
    - rawmaterials-reference
    - reps-austria-reference
    - reps-barcelona-reference
    - reps-belgium-reference
    - reps-bulgaria-reference
    - reps-ceskarepublika-reference
    - reps-croatia-reference
    - reps-cyprus-reference
    - reps-denmark-reference
    - reps-deutschland-reference
    - reps-estonia-reference
    - reps-finland-reference
    - reps-france-reference
    - reps-greece-reference
    - reps-hungary-reference
    - reps-ireland-reference
    - reps-italy-reference
    - reps-latvia-reference
    - reps-lietuva-reference
    - reps-luxembourg-reference
    - reps-malta-reference
    - reps-netherlands-reference
    - reps-polska-reference
    - reps-portugal-reference
    - reps-romania-reference
    - reps-slovakia-reference
    - reps-slovenia-reference
    - reps-spain-reference
    - reps-sweden-reference
    - reps-unitedkingdom-reference
    - road-safety-reference
    - roma-reference
    - safety_alerts-reference
    - scicnet-reference
    - service-catalogue-reference
    - sfc2014-reference
    - speech-repository-reference
    - sport-reference
    - srb-reference
    - stages-reference
    - stages2-reference
    - taxedu-reference
    - taxud-reference
    - teachers-corner-reference
    - vocational-skills-week-reference
    - youthwiki-reference
    - youth-reference
pipeline:
  composer:
    image: fpfis/php71-build
    secrets: [ github_api_token ]
    commands:
      - export CHECKSUM=$(md5sum composer.lock | cut -d ' ' -f 1)
      - tar -xzf /cache/composer/$${CHECKSUM}.tar.gz || composer install --ansi --no-suggest && tar -czf /cache/composer/$${CHECKSUM}.tar.gz ./vendor/
      - ./vendor/bin/run project:create-project --ansi --repository=ec-europa/${REPOSITORY}
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache
  phpcs:
    image: fpfis/php71-build
    when:
      status: [ success, failure ]
    commands:
      - ./vendor/bin/run project:run-phpcs --ansi --repository=ec-europa/${REPOSITORY}
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache