clone:
  git:
    image: plugins/git:next

workspace:
  base: /test
  path: downstream

services:
  web:
    image: fpfis/php71-build
    environment:
      - TOOLKIT_ENV_PROPS=/test/downstream/vendor/ec-europa/toolkit/includes/phing/props/drone.props

pipeline:

  composer:
    image: fpfis/php71-build
    secrets: [ github_api_token ]
    commands:
      - export CHECKSUM=$(md5sum composer.lock | cut -d ' ' -f 1)
      - tar -xzf /cache/composer/$${CHECKSUM}.tar.gz || composer install --ansi --no-suggest && tar -czf /cache/composer/$${CHECKSUM}.tar.gz ./vendor/
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  encasia-reference:
    image: fpfis/php71-build
    secrets: [ github_api_token ]
    when:
      status: [ success, failure ]
      matrix:
        MACHINE_NAME: machine-1
    commands:
      - ./vendor/bin/run project:create-project --repository=ec-europa/encasia-reference --ansi
      - ./vendor/bin/run project:run-phpcs --repository=ec-europa/encasia-reference --ansi
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  ener-reference:
    image: fpfis/php71-build
    secrets: [ github_api_token ]
    when:
      status: [ success, failure ]
      matrix:
        MACHINE_NAME: machine-1
    commands:
      - ./vendor/bin/run project:create-project --repository=ec-europa/ener-reference --ansi
      - ./vendor/bin/run project:run-phpcs --repository=ec-europa/ener-reference --ansi
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  enrd-reference:
    image: fpfis/php71-build
    secrets: [ github_api_token ]
    when:
      status: [ success, failure ]
      matrix:
        MACHINE_NAME: machine-1
    commands:
      - ./vendor/bin/run project:create-project --repository=ec-europa/enrd-reference --ansi
      - ./vendor/bin/run project:run-phpcs --repository=ec-europa/enrd-reference --ansi
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  env-efe-reference:
    image: fpfis/php71-build
    secrets: [ github_api_token ]
    when:
      status: [ success, failure ]
      matrix:
        MACHINE_NAME: machine-1
    commands:
      - ./vendor/bin/run project:create-project --repository=ec-europa/env-efe-reference --ansi
      - ./vendor/bin/run project:run-phpcs --repository=ec-europa/env-efe-reference --ansi
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  ewrc-reference:
    image: fpfis/php71-build
    secrets: [ github_api_token ]
    when:
      status: [ success, failure ]
      matrix:
        MACHINE_NAME: machine-1
    commands:
      - ./vendor/bin/run project:create-project --repository=ec-europa/ewrc-reference --ansi
      - ./vendor/bin/run project:run-phpcs --repository=ec-europa/ewrc-reference --ansi
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  expert-pane-reference:
    image: fpfis/php71-build
    secrets: [ github_api_token ]
    when:
      status: [ success, failure ]
      matrix:
        MACHINE_NAME: machine-1
    commands:
      - ./vendor/bin/run project:create-project --repository=ec-europa/expert-pane-reference --ansi
      - ./vendor/bin/run project:run-phpcs --repository=ec-europa/expert-pane-reference --ansi
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  eych-reference:
    image: fpfis/php71-build
    secrets: [ github_api_token ]
    when:
      status: [ success, failure ]
      matrix:
        MACHINE_NAME: machine-1
    commands:
      - ./vendor/bin/run project:create-project --repository=ec-europa/eych-reference --ansi
      - ./vendor/bin/run project:run-phpcs --repository=ec-europa/eych-reference --ansi
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  farnet-reference:
    image: fpfis/php71-build
    secrets: [ github_api_token ]
    when:
      status: [ success, failure ]
      matrix:
        MACHINE_NAME: machine-1
    commands:
      - ./vendor/bin/run project:create-project --repository=ec-europa/farnet-reference --ansi
      - ./vendor/bin/run project:run-phpcs --repository=ec-europa/farnet-reference --ansi
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  growth-reference:
    image: fpfis/php71-build
    secrets: [ github_api_token ]
    when:
      status: [ success, failure ]
      matrix:
        MACHINE_NAME: machine-1
    commands:
      - ./vendor/bin/run project:create-project --repository=ec-europa/growth-reference --ansi
      - ./vendor/bin/run project:run-phpcs --repository=ec-europa/growth-reference --ansi
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  health-reference:
    image: fpfis/php71-build
    secrets: [ github_api_token ]
    when:
      status: [ success, failure ]
      matrix:
        MACHINE_NAME: machine-1
    commands:
      - ./vendor/bin/run project:create-project --repository=ec-europa/health-reference --ansi
      - ./vendor/bin/run project:run-phpcs --repository=ec-europa/health-reference --ansi
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  home-affairs-reference:
    image: fpfis/php71-build
    secrets: [ github_api_token ]
    when:
      status: [ success, failure ]
      matrix:
        MACHINE_NAME: machine-1
    commands:
      - ./vendor/bin/run project:create-project --repository=ec-europa/home-affairs-reference --ansi
      - ./vendor/bin/run project:run-phpcs --repository=ec-europa/home-affairs-reference --ansi
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  horizon2020-reference:
    image: fpfis/php71-build
    secrets: [ github_api_token ]
    when:
      status: [ success, failure ]
      matrix:
        MACHINE_NAME: machine-1
    commands:
      - ./vendor/bin/run project:create-project --repository=ec-europa/horizon2020-reference --ansi
      - ./vendor/bin/run project:run-phpcs --repository=ec-europa/horizon2020-reference --ansi
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  iee-projects-reference:
    image: fpfis/php71-build
    secrets: [ github_api_token ]
    when:
      status: [ success, failure ]
      matrix:
        MACHINE_NAME: machine-1
    commands:
      - ./vendor/bin/run project:create-project --repository=ec-europa/iee-projects-reference --ansi
      - ./vendor/bin/run project:run-phpcs --repository=ec-europa/iee-projects-reference --ansi
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  inforegio-reference:
    image: fpfis/php71-build
    secrets: [ github_api_token ]
    when:
      status: [ success, failure ]
      matrix:
        MACHINE_NAME: machine-2
    commands:
      - ./vendor/bin/run project:create-project --repository=ec-europa/inforegio-reference --ansi
      - ./vendor/bin/run project:run-phpcs --repository=ec-europa/inforegio-reference --ansi
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  inea-reference:
    image: fpfis/php71-build
    secrets: [ github_api_token ]
    when:
      status: [ success, failure ]
      matrix:
        MACHINE_NAME: machine-2
    commands:
      - ./vendor/bin/run project:create-project --repository=ec-europa/inea-reference --ansi
      - ./vendor/bin/run project:run-phpcs --repository=ec-europa/inea-reference --ansi
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  inseparable-reference:
    image: fpfis/php71-build
    secrets: [ github_api_token ]
    when:
      status: [ success, failure ]
      matrix:
        MACHINE_NAME: machine-2
    commands:
      - ./vendor/bin/run project:create-project --repository=ec-europa/inseparable-reference --ansi
      - ./vendor/bin/run project:run-phpcs --repository=ec-europa/inseparable-reference --ansi
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  isa-reference:
    image: fpfis/php71-build
    secrets: [ github_api_token ]
    when:
      status: [ success, failure ]
      matrix:
        MACHINE_NAME: machine-2
    commands:
      - ./vendor/bin/run project:create-project --repository=ec-europa/isa-reference --ansi
      - ./vendor/bin/run project:run-phpcs --repository=ec-europa/isa-reference --ansi
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  jrccties-reference:
    image: fpfis/php71-build
    secrets: [ github_api_token ]
    when:
      status: [ success, failure ]
      matrix:
        MACHINE_NAME: machine-2
    commands:
      - ./vendor/bin/run project:create-project --repository=ec-europa/jrccties-reference --ansi
      - ./vendor/bin/run project:run-phpcs --repository=ec-europa/jrccties-reference --ansi
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  jrcsh-reference:
    image: fpfis/php71-build
    secrets: [ github_api_token ]
    when:
      status: [ success, failure ]
      matrix:
        MACHINE_NAME: machine-2
    commands:
      - ./vendor/bin/run project:create-project --repository=ec-europa/jrcsh-reference --ansi
      - ./vendor/bin/run project:run-phpcs --repository=ec-europa/jrcsh-reference --ansi
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  kci-reference:
    image: fpfis/php71-build
    secrets: [ github_api_token ]
    when:
      status: [ success, failure ]
      matrix:
        MACHINE_NAME: machine-2
    commands:
      - ./vendor/bin/run project:create-project --repository=ec-europa/kci-reference --ansi
      - ./vendor/bin/run project:run-phpcs --repository=ec-europa/kci-reference --ansi
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  know4pol-reference:
    image: fpfis/php71-build
    secrets: [ github_api_token ]
    when:
      status: [ success, failure ]
      matrix:
        MACHINE_NAME: machine-2
    commands:
      - ./vendor/bin/run project:create-project --repository=ec-europa/know4pol-reference --ansi
      - ./vendor/bin/run project:run-phpcs --repository=ec-europa/know4pol-reference --ansi
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  mare-emd-reference:
    image: fpfis/php71-build
    secrets: [ github_api_token ]
    when:
      status: [ success, failure ]
      matrix:
        MACHINE_NAME: machine-2
    commands:
      - ./vendor/bin/run project:create-project --repository=ec-europa/mare-emd-reference --ansi
      - ./vendor/bin/run project:run-phpcs --repository=ec-europa/mare-emd-reference --ansi
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  mare-magaz-reference:
    image: fpfis/php71-build
    secrets: [ github_api_token ]
    when:
      status: [ success, failure ]
      matrix:
        MACHINE_NAME: machine-2
    commands:
      - ./vendor/bin/run project:create-project --repository=ec-europa/mare-magaz-reference --ansi
      - ./vendor/bin/run project:run-phpcs --repository=ec-europa/mare-magaz-reference --ansi
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  mariecurie-actions-reference:
    image: fpfis/php71-build
    secrets: [ github_api_token ]
    when:
      status: [ success, failure ]
      matrix:
        MACHINE_NAME: machine-2
    commands:
      - ./vendor/bin/run project:create-project --repository=ec-europa/mariecurie-actions-reference --ansi
      - ./vendor/bin/run project:run-phpcs --repository=ec-europa/mariecurie-actions-reference --ansi
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  mariecurie2-reference:
    image: fpfis/php71-build
    secrets: [ github_api_token ]
    when:
      status: [ success, failure ]
      matrix:
        MACHINE_NAME: machine-2
    commands:
      - ./vendor/bin/run project:create-project --repository=ec-europa/mariecurie2-reference --ansi
      - ./vendor/bin/run project:run-phpcs --repository=ec-europa/mariecurie2-reference --ansi
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  maritime-affaires-reference:
    image: fpfis/php71-build
    secrets: [ github_api_token ]
    when:
      status: [ success, failure ]
      matrix:
        MACHINE_NAME: machine-2
    commands:
      - ./vendor/bin/run project:create-project --repository=ec-europa/maritime-affaires-reference --ansi
      - ./vendor/bin/run project:run-phpcs --repository=ec-europa/maritime-affaires-reference --ansi
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

matrix:
  MACHINE_NAME:
    - machine-1
    - machine-2

