clone:
  git:
    image: plugins/git:next

workspace:
  base: /test
  path: downstream

services:
  web:
    image: fpfis/php71-build
    environment:
      - TOOLKIT_ENV_PROPS=/test/downstream/vendor/ec-europa/toolkit/includes/phing/props/drone.props

pipeline:

  composer:
    image: fpfis/php71-build
    secrets: [ github_api_token ]
    commands:
      - export CHECKSUM=$(md5sum composer.lock | cut -d ' ' -f 1)
      - tar -xzf /cache/composer/$${CHECKSUM}.tar.gz || composer install --ansi --no-suggest && tar -czf /cache/composer/$${CHECKSUM}.tar.gz ./vendor/
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  anti-fraud-reference:
    image: fpfis/php71-build
    secrets: [ github_api_token ]
    when:
      status: [ success, failure ]
      matrix:
        MACHINE_NAME: machine-1
    commands:
      - timeout 60 ./vendor/bin/run project:create-project --repository=ec-europa/anti-fraud-reference --ansi
      - ./vendor/bin/run project:run-phpcs --repository=ec-europa/anti-fraud-reference --ansi
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  chafea-reference:
    image: fpfis/php71-build
    secrets: [ github_api_token ]
    when:
      status: [ success, failure ]
      matrix:
        MACHINE_NAME: machine-1
    commands:
      - timeout 60 ./vendor/bin/run project:create-project --repository=ec-europa/chafea-reference --ansi
      - ./vendor/bin/run project:run-phpcs --repository=ec-europa/chafea-reference --ansi
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  dt_info_reference:
    image: fpfis/php71-build
    secrets: [ github_api_token ]
    when:
      status: [ success, failure ]
      matrix:
        MACHINE_NAME: machine-2
    commands:
      - timeout 60 ./vendor/bin/run project:create-project --repository=ec-europa/dt_info_reference --ansi
      - ./vendor/bin/run project:run-phpcs --repository=ec-europa/dt_info_reference --ansi
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  eac-eqf-reference:
    image: fpfis/php71-build
    secrets: [ github_api_token ]
    when:
      status: [ success, failure ]
      matrix:
        MACHINE_NAME: machine-2
    commands:
      - timeout 60 ./vendor/bin/run project:create-project --repository=ec-europa/eac-eqf-reference --ansi
      - ./vendor/bin/run project:run-phpcs --repository=ec-europa/eac-eqf-reference --ansi
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

matrix:
  MACHINE_NAME:
    - machine-1
    - machine-2

