clone:
  git:
    image: plugins/git:next

workspace:
  base: /test
  path: downstream

services:
  web:
    image: fpfis/php71-build
    environment:
      - TOOLKIT_ENV_PROPS=/test/downstream/vendor/ec-europa/toolkit/includes/phing/props/drone.props

pipeline:

  composer:
    image: fpfis/php71-build
    secrets: [ github_api_token ]
    commands:
      - export CHECKSUM=$(md5sum composer.lock | cut -d ' ' -f 1)
      - tar -xzf /cache/composer/$${CHECKSUM}.tar.gz || composer install --ansi --no-suggest && tar -czf /cache/composer/$${CHECKSUM}.tar.gz ./vendor/
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  agm-reference:
    image: fpfis/php71-build
    secrets: [ github_api_token ]
    when:
      status: [ success, failure ]
      matrix:
        MACHINE_NAME: machine-1
    commands:
      - ./vendor/bin/run project:create-project --repository=ec-europa/agm-reference --ansi
      - ./vendor/bin/run project:run-phpcs --repository=ec-europa/agm-reference --ansi
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  agri-eip-reference:
    image: fpfis/php71-build
    secrets: [ github_api_token ]
    when:
      status: [ success, failure ]
      matrix:
        MACHINE_NAME: machine-1
    commands:
      - ./vendor/bin/run project:create-project --repository=ec-europa/agri-eip-reference --ansi
      - ./vendor/bin/run project:run-phpcs --repository=ec-europa/agri-eip-reference --ansi
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  amr-reference:
    image: fpfis/php71-build
    secrets: [ github_api_token ]
    when:
      status: [ success, failure ]
      matrix:
        MACHINE_NAME: machine-1
    commands:
      - ./vendor/bin/run project:create-project --repository=ec-europa/amr-reference --ansi
      - ./vendor/bin/run project:run-phpcs --repository=ec-europa/amr-reference --ansi
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  anti-fraud-reference:
    image: fpfis/php71-build
    secrets: [ github_api_token ]
    when:
      status: [ success, failure ]
      matrix:
        MACHINE_NAME: machine-1
    commands:
      - ./vendor/bin/run project:create-project --repository=ec-europa/anti-fraud-reference --ansi
      - ./vendor/bin/run project:run-phpcs --repository=ec-europa/anti-fraud-reference --ansi
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  antitrafficking-reference:
    image: fpfis/php71-build
    secrets: [ github_api_token ]
    when:
      status: [ success, failure ]
      matrix:
        MACHINE_NAME: machine-1
    commands:
      - ./vendor/bin/run project:create-project --repository=ec-europa/antitrafficking-reference --ansi
      - ./vendor/bin/run project:run-phpcs --repository=ec-europa/antitrafficking-reference --ansi
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  argiculture-reference:
    image: fpfis/php71-build
    secrets: [ github_api_token ]
    when:
      status: [ success, failure ]
      matrix:
        MACHINE_NAME: machine-1
    commands:
      - ./vendor/bin/run project:create-project --repository=ec-europa/argiculture-reference --ansi
      - ./vendor/bin/run project:run-phpcs --repository=ec-europa/argiculture-reference --ansi
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  basext-reference:
    image: fpfis/php71-build
    secrets: [ github_api_token ]
    when:
      status: [ success, failure ]
      matrix:
        MACHINE_NAME: machine-1
    commands:
      - ./vendor/bin/run project:create-project --repository=ec-europa/basext-reference --ansi
      - ./vendor/bin/run project:run-phpcs --repository=ec-europa/basext-reference --ansi
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  cem-reference:
    image: fpfis/php71-build
    secrets: [ github_api_token ]
    when:
      status: [ success, failure ]
      matrix:
        MACHINE_NAME: machine-1
    commands:
      - ./vendor/bin/run project:create-project --repository=ec-europa/cem-reference --ansi
      - ./vendor/bin/run project:run-phpcs --repository=ec-europa/cem-reference --ansi
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  chafea-reference:
    image: fpfis/php71-build
    secrets: [ github_api_token ]
    when:
      status: [ success, failure ]
      matrix:
        MACHINE_NAME: machine-1
    commands:
      - ./vendor/bin/run project:create-project --repository=ec-europa/chafea-reference --ansi
      - ./vendor/bin/run project:run-phpcs --repository=ec-europa/chafea-reference --ansi
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  cim-reference:
    image: fpfis/php71-build
    secrets: [ github_api_token ]
    when:
      status: [ success, failure ]
      matrix:
        MACHINE_NAME: machine-2
    commands:
      - ./vendor/bin/run project:create-project --repository=ec-europa/cim-reference --ansi
      - ./vendor/bin/run project:run-phpcs --repository=ec-europa/cim-reference --ansi
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  clima-reference:
    image: fpfis/php71-build
    secrets: [ github_api_token ]
    when:
      status: [ success, failure ]
      matrix:
        MACHINE_NAME: machine-2
    commands:
      - ./vendor/bin/run project:create-project --repository=ec-europa/clima-reference --ansi
      - ./vendor/bin/run project:run-phpcs --repository=ec-europa/clima-reference --ansi
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  comm-digitaltransformation-blog-reference:
    image: fpfis/php71-build
    secrets: [ github_api_token ]
    when:
      status: [ success, failure ]
      matrix:
        MACHINE_NAME: machine-2
    commands:
      - ./vendor/bin/run project:create-project --repository=ec-europa/comm-digitaltransformation-blog-reference --ansi
      - ./vendor/bin/run project:run-phpcs --repository=ec-europa/comm-digitaltransformation-blog-reference --ansi
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  commpo-reference:
    image: fpfis/php71-build
    secrets: [ github_api_token ]
    when:
      status: [ success, failure ]
      matrix:
        MACHINE_NAME: machine-2
    commands:
      - ./vendor/bin/run project:create-project --repository=ec-europa/commpo-reference --ansi
      - ./vendor/bin/run project:run-phpcs --repository=ec-europa/commpo-reference --ansi
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  consular-protection-reference:
    image: fpfis/php71-build
    secrets: [ github_api_token ]
    when:
      status: [ success, failure ]
      matrix:
        MACHINE_NAME: machine-2
    commands:
      - ./vendor/bin/run project:create-project --repository=ec-europa/consular-protection-reference --ansi
      - ./vendor/bin/run project:run-phpcs --repository=ec-europa/consular-protection-reference --ansi
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  creativeeurope-reference:
    image: fpfis/php71-build
    secrets: [ github_api_token ]
    when:
      status: [ success, failure ]
      matrix:
        MACHINE_NAME: machine-2
    commands:
      - ./vendor/bin/run project:create-project --repository=ec-europa/creativeeurope-reference --ansi
      - ./vendor/bin/run project:run-phpcs --repository=ec-europa/creativeeurope-reference --ansi
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  crosportal-reference:
    image: fpfis/php71-build
    secrets: [ github_api_token ]
    when:
      status: [ success, failure ]
      matrix:
        MACHINE_NAME: machine-2
    commands:
      - ./vendor/bin/run project:create-project --repository=ec-europa/crosportal-reference --ansi
      - ./vendor/bin/run project:run-phpcs --repository=ec-europa/crosportal-reference --ansi
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  culture-reference:
    image: fpfis/php71-build
    secrets: [ github_api_token ]
    when:
      status: [ success, failure ]
      matrix:
        MACHINE_NAME: machine-2
    commands:
      - ./vendor/bin/run project:create-project --repository=ec-europa/culture-reference --ansi
      - ./vendor/bin/run project:run-phpcs --repository=ec-europa/culture-reference --ansi
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

matrix:
  MACHINE_NAME:
    - machine-1
    - machine-2

