# ==============================================================================
# Pull request clone ===========================================================
# ==============================================================================
# Use plugin to checkout pull requests for caching issue:
# https://github.com/drone/drone/issues/2390
# ==============================================================================
clone:
  git:
    image: plugins/git:next

# ==============================================================================
# Workspace location.
# ==============================================================================
workspace:
  base: /test
  path: downstream

# ==============================================================================
# Downstream pipelines
# ==============================================================================
pipeline:

  toolkit-demo:
    image: plugins/downstream
    server: https://drone.fpfis.eu
    secrets: [ downstream_token ]
    fork: true
    repositories:
      - verbruggenalex/downstream@${DOWNSTREAM_BRANCH:-toolkit/demo}
    params:
      - DEMO_TIMEOUT=${DEMO_TIMEOUT}
      - DEMO_BRANCH=${DEMO_BRANCH}
      - DEMO_REPOSITORY=${DEMO_REPOSITORY}