clone:
  git:
    image: plugins/git:next

workspace:
  base: /test
  path: downstream

services:
  web:
    image: fpfis/php71-build
    environment:
      - TOOLKIT_ENV_PROPS=/test/downstream/vendor/ec-europa/toolkit/includes/phing/props/drone.props

pipeline:

  composer:
    image: fpfis/php71-build
    secrets: [ github_api_token ]
    commands:
      - export CHECKSUM=$(md5sum composer.lock | cut -d ' ' -f 1)
      - tar -xzf /cache/composer/$${CHECKSUM}.tar.gz || composer install --ansi --no-suggest && tar -czf /cache/composer/$${CHECKSUM}.tar.gz ./vendor/
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  erasmusplus2-reference:
    image: fpfis/php71-build
    secrets: [ github_api_token ]
    when:
      status: [ success, failure ]
      matrix:
        MACHINE_NAME: machine-1
    commands:
      - timeout 60 ./vendor/bin/run project:create-project --repository=ec-europa/erasmusplus2-reference --ansi
      - ls -la repositories/ec-europa/erasmusplus2-reference
      - mkdir template && ./vendor/bin/run toolkit:build-template --template=ec-europa.platform.2 --ansi --progress-delay=300
      - ./vendor/bin/run drupal:make-to-composer --make-file=repositories/ec-europa/erasmusplus2-reference/resources/site.make --ansi --progress-delay=300
      - ./vendor/bin/run toolkit:install-template --ansi --progress-delay=300
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache
  tunnel:
    image: fpfis/drone-frpc-plugin:latest
    secrets: [ frpc_token, frpc_server ]
    environment:
      - PLUGIN_ENDPOINT=web:8080
      - PLUGIN_GEN_AUTH=yes
      - PLUGIN_DOMAIN=${DRONE_REPO_NAME}-${DRONE_BUILD_NUMBER}-${DRONE_JOB_NUMBER}.ci.fpfis.tech.ec.europa.eu
      - PLUGIN_URL_OUTPUT_FILE=/test/toolkit/.frpc
    when:
      status: [ success, failure ]
      matrix:
        MACHINE_NAME: machine-1

matrix:
  MACHINE_NAME:
    - machine-1

