clone:
  git:
    image: plugins/git:next

workspace:
  base: /test
  path: downstream

services:
  web:
    image: fpfis/php71-build
    environment:
      - TOOLKIT_ENV_PROPS=/test/downstream/vendor/ec-europa/toolkit/includes/phing/props/drone.props

pipeline:

  composer:
    image: fpfis/php71-build
    secrets: [ github_api_token ]
    commands:
      - export CHECKSUM=$(md5sum composer.lock | cut -d ' ' -f 1)
      - tar -xzf /cache/composer/$${CHECKSUM}.tar.gz || composer install --ansi --no-suggest && tar -czf /cache/composer/$${CHECKSUM}.tar.gz ./vendor/
      - ./vendor/bin/run project:create-project --ansi --repository=${REPOSITORY}
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  agm-reference:
    image: fpfis/php71-build
    when:
      status: [ success, failure ]
      matrix:
        - MACHINE_NAME=machine-1
    commands:
      - ./vendor/bin/run project:run-phpcs --ansi --repository=ec-europa/agm-reference

  agri-eip-reference:
    image: fpfis/php71-build
    when:
      status: [ success, failure ]
      matrix:
        - MACHINE_NAME=machine-1
    commands:
      - ./vendor/bin/run project:run-phpcs --ansi --repository=ec-europa/agri-eip-reference

  amr-reference:
    image: fpfis/php71-build
    when:
      status: [ success, failure ]
      matrix:
        - MACHINE_NAME=machine-1
    commands:
      - ./vendor/bin/run project:run-phpcs --ansi --repository=ec-europa/amr-reference

  anti-fraud-reference:
    image: fpfis/php71-build
    when:
      status: [ success, failure ]
      matrix:
        - MACHINE_NAME=machine-1
    commands:
      - ./vendor/bin/run project:run-phpcs --ansi --repository=ec-europa/anti-fraud-reference

  antitrafficking-reference:
    image: fpfis/php71-build
    when:
      status: [ success, failure ]
      matrix:
        - MACHINE_NAME=machine-1
    commands:
      - ./vendor/bin/run project:run-phpcs --ansi --repository=ec-europa/antitrafficking-reference

  argiculture-reference:
    image: fpfis/php71-build
    when:
      status: [ success, failure ]
      matrix:
        - MACHINE_NAME=machine-2
    commands:
      - ./vendor/bin/run project:run-phpcs --ansi --repository=ec-europa/argiculture-reference

  basext-reference:
    image: fpfis/php71-build
    when:
      status: [ success, failure ]
      matrix:
        - MACHINE_NAME=machine-2
    commands:
      - ./vendor/bin/run project:run-phpcs --ansi --repository=ec-europa/basext-reference

  cem-reference:
    image: fpfis/php71-build
    when:
      status: [ success, failure ]
      matrix:
        - MACHINE_NAME=machine-2
    commands:
      - ./vendor/bin/run project:run-phpcs --ansi --repository=ec-europa/cem-reference

  chafea-reference:
    image: fpfis/php71-build
    when:
      status: [ success, failure ]
      matrix:
        - MACHINE_NAME=machine-2
    commands:
      - ./vendor/bin/run project:run-phpcs --ansi --repository=ec-europa/chafea-reference

  cim-reference:
    image: fpfis/php71-build
    when:
      status: [ success, failure ]
      matrix:
        - MACHINE_NAME=machine-2
    commands:
      - ./vendor/bin/run project:run-phpcs --ansi --repository=ec-europa/cim-reference

matrix:
  MACHINE_NAME:
    - machine-1
    - machine-2

