clone:
  git:
    image: plugins/git:next
workspace:
  base: /toolkit
  path: dev-master
services:
  web:
    image: fpfis/php56-build
    environment:
      - DOCUMENT_ROOT=/test/toolkit/build
  mysql:
    image: percona/percona-server:5.6
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
pipeline:
  visreg:
    image: backstopjs/backstopjs
    commands:
      - backstop init
  toolkit:
    image: fpfis/php56-build
    secrets: [ GITHUB_API_TOKEN ]
    group: setup
    commands:
      - rm -rf .git && git init
      - git pull https://$${GITHUB_API_TOKEN}@github.com/$${DOWNSTREAM_OWNER}/$${DOWNSTREAM_REPO}.git
      - git checkout $${DOWNSTREAM_BRANCH}
      - composer require ec-europa/toolkit:dev-feature/MULTISITE-19985
      - mkdir includes && ln -s $$(pwd)/vendor/ec-europa/toolkit/includes/docker $$(pwd)/includes/docker
      - cp vendor/ec-europa/toolkit/includes/phing/props/drone.props build.develop.props
    volumes:
      - /cache:/cache
  build:
    image: fpfis/php56-build
    group: build
    commands:
      - ./toolkit/phing build-platform build-subsite-dev -logger phing.listener.AnsiColorLogger
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache
  asda:
    image: fpfis/drone-plugin-asda
    group: build
    target: /test/toolkit/dump.sql
    website: ${DOWNSTREAM_REPO%%-reference}
    secrets: [ asda_url ]
    volumes:
      - /cache:/cache
  solr:
    image: fpfis/solr5
    group: build
    detach: true
    when:
      event: [ push, pull_request, tag ]
  install:
    image: fpfis/php56-build
    group: install
    commands:
      - ./toolkit/phing install-clone docker-backstop-generate drush-gdpr-dump -D'database-file'='/test/toolkit/dump.sql' -logger phing.listener.AnsiColorLogger
      - ./toolkit/drush -r build sql-create -y
      - ./toolkit/drush -r build sqlc < /test/toolkit/dump.sql
      - tar -czf ../build-dev-master.tar.gz --exclude='./.drone.yml' --exclude='.git/' --exclude='./dump.sql' .
      - tar -czf ../asda-dev-master.tar.gz dump.sql backstop_data/ backstop.json
  visreg:
    image: backstopjs/backstopjs
    commands:
      - cp -f includes/docker/docker-backstopjs/core/util/runPuppet.js /usr/local/lib/node_modules/backstopjs/core/util/runPuppet.js
      - cp -f includes/docker/docker-backstopjs/core/util/compare/index.js /usr/local/lib/node_modules/backstopjs/core/util/compare/index.js
      - backstop reference
  upload-build:
    image: drillster/drone-rsync
    user: web_asda
    secrets: [ plugin_key, plugin_hosts ]
    source: ../build-dev-${DOWNSTREAM_BRANCH}.tar.gz
    target: ${DOWNSTREAM_OWNER}/${DOWNSTREAM_REPO}/dist/
  upload-asda:
    image: drillster/drone-rsync
    user: web_asda
    secrets: [ plugin_key, plugin_hosts ]
    source: ../asda-dev-${DOWNSTREAM_BRANCH}.tar.gz
    target: ${DOWNSTREAM_OWNER}/${DOWNSTREAM_REPO}/asda/