clone:
  git:
    image: plugins/git:next

workspace:
  base: /test
  path: downstream

services:
  web:
    image: fpfis/php71-build
    environment:
      - TOOLKIT_ENV_PROPS=/test/downstream/vendor/ec-europa/toolkit/includes/phing/props/drone.props

pipeline:

  composer:
    image: fpfis/php71-build
    secrets: [ github_api_token ]
    commands:
      - composer install --ansi --no-suggest
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  eu-aid-reference:
    image: fpfis/php71-build
    secrets: [ github_api_token ]
    when:
      status: [ success, failure ]
      matrix:
        MACHINE_NAME: machine-1
    commands:
      - timeout 60 ./vendor/bin/run project:create-project --repository=ec-europa/eu-aid-reference --ansi
      - mkdir template && ./vendor/bin/run toolkit:build-template --template=ec-europa.platform.2 --ansi --progress-delay=300
      - ./vendor/bin/run drupal:make-to-composer --make-file=repositories/ec-europa/eu-aid-reference/resources/site.make --ansi --progress-delay=300
      - ./vendor/bin/run toolkit:install-template --ansi --progress-delay=300
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

matrix:
  MACHINE_NAME:
    - machine-1

