  {repo_name}:
    image: fpfis/php{php_version}-build
    secrets: [ github_api_token ]
    when:
      status: [ success, failure ]
      matrix:
        MACHINE_NAME: {machine_name}
    commands:
      - timeout 6Os ./vendor/bin/run project:create-project --repository={repo_owner}/{repo_name} --ansi
      - ./vendor/bin/run project:run-phpcs --repository={repo_owner}/{repo_name} --ansi
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

