clone:
  git:
    image: plugins/git:next
workspace:
  base: /test
  path: downstream
services:
  web:
    image: fpfis/php{php_version}-build
    environment:
      - TOOLKIT_ENV_PROPS=/test/downstream/vendor/ec-europa/toolkit/includes/phing/props/drone.props
pipeline:
  setup:
    image: fpfis/php{php_version}-build
    group: setup
    commands:
      - composer require ec-europa/toolkit:dev-master --ansi --no-suggest
      - PROJECT=$(pwd) composer run-script toolkit-install -d ./vendor/ec-europa/toolkit
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache
